### ISSUE TITLE
Logging out on 403 errors

### ISSUE THREAD

**Issue by dinodeSimon** [josx/ra-data-feathers#111]
We are working with an API that sends a 403 HTTP status code when trying to delete an item that a user doesn't have permissions to delete. Currently the auto provider is seeing this 403 response and logging the user out completely.

Looking back through the history the addition of the piece of code to log the users out on 403 responses in addition to 401 was added to the auth provider a year ago.

https://github.com/josx/ra-data-feathers/commit/574ee17ac4028407eb32983dc08293c31840dcfe

Is it possible to change this so that the http codes which trigger a logout can be passed in with the options? That way we choose to log out on 401 responses and handle 403 responses for a particular item rather than logging the user out.

**Comment by josx** [comment]
Ok, what do you think if we can it as an option?
Can you make a PR with that?

**Comment by dinodeSimon** [comment]
Hi José,

No problems, we will have a think about a neat way to do it and put a PR up in the next couple of days.

**Comment by TheHyphen** [comment]
Hi, we've made a PR here: https://github.com/josx/ra-data-feathers/pull/112
Any thoughts?

**Comment by josx** [comment]
@TheHyphen I have merged you code, I think will help @dinodeSimon

**Comment by TheHyphen** [comment]
Thank you! When do you think this change might make it to an npm release?

**Comment by josx** [comment]
Here [v2.2.1](https://github.com/josx/ra-data-feathers/releases/tag/v2.2.1)

**Comment by TheHyphen** [comment]
Thanks a ton! ✌️
