### ISSUE TITLE
Socketio

### ISSUE THREAD

**Issue by Globik** [josx/ra-data-feathers#128]
Is there any example getting work with socketio plus react-admin?

**Comment by josx** [comment]
I have never used with socket.io, but some time ago we discuss websockets in this issue #83 
Maybe can give you some clues.

Would be nice, if you can make an example on that.

**Comment by josx** [comment]
@Globik please give us feedback on what happened, surely your experience in this would clarify others too.

**Comment by Globik** [comment]
I've decided to use dataProvider based on websocket. No help of ra-data-feathers.

**Comment by josx** [comment]
@Globik A colleague need to do a dataprovider based on websocket. Do you have an example code or repo?
