### ISSUE TITLE
GET_ONE should accept params

### ISSUE THREAD

**Issue by Joelith** [josx/ra-data-feathers#131]
For my feathers backend I use some additional parameters to pass to the server (to modify the behaviour of the output). But ra-data-feathers doesn't pass the params down to Feathers. If you change the the _reactAdmin.GET_ONE case in the restClient file to this:

```
case _reactAdmin.GET_ONE:
    var id = params.id;
    return service.get(id, params);
```

Then it works. Happy to send a pull request through

**Comment by josx** [comment]
ok, please do a PR

**Comment by josx** [comment]
I need to upgrade, so i have done this PR https://github.com/josx/ra-data-feathers/pull/133
