### ISSUE TITLE
Logout problem react-admin 3, feathers 4

### ISSUE THREAD

**Issue by leo-orellana** [josx/ra-data-feathers#132]
Hi, I'm using react-admin 3 and feathers 4.4.1. 
I installed version 2.4.1 of the data provider and it works correctly but the system logs me out when I refresh the page or open it in a new tab. I could see that version 2.4.1 is 2 commits behind the master branch. 
I downloaded and used the master branch code because I saw that the commit [9e8fdc099c883d92e2386c7bf9b3f560fbcbfdd6](https://github.com/josx/ra-data-feathers/commit/9e8fdc099c883d92e2386c7bf9b3f560fbcbfdd6) adds reauthentication logic in AUTH_CHECK and the session logout problem was fixed. Could you get an updated version with that fix? 
Thank you!

**Comment by josx** [comment]
New release done !

Check 
- https://github.com/josx/ra-data-feathers/releases/tag/v2.5.0
- https://www.npmjs.com/package/ra-data-feathers
