### ISSUE TITLE
Query filter not working for nested fields

### ISSUE THREAD

**Issue by fabioptoi** [josx/ra-data-feathers#137]
Hello!

I recently updated my project from `aor-feathers-client` to `ra-data-feathers` and I wanted to create filters for nested field with comparison operators.

My react-admin filter code looks like this:
```javascript
<Filter {...props}>
  <NumberInput label="Rating" source="rating.score[$gt]" alwaysOn />
</Filter>
```

As you can see, I have a nested field `rating.score` which I would like to apply a greater than comparison. When I look at the request query string, I have the following:

`?rating%5Bscore%5D%5B%24gt%5D=1`

which decodes to

`?rating[score][$gt]=1`

I believe that the feathers api expects something like `?rating.score[$gt]=1` to correctly query a nested field and apply to comparison operator (I tested this using Postman and it works)

I searched past issues related to mine and I found https://github.com/josx/ra-data-feathers/issues/90, where there is a suggestion to create a conditional flatting object function that flat only props not in ($lte, $gt, and the other on the feathers doc) on this line https://github.com/josx/ra-data-feathers/blob/master/src/restClient.js#L60, which I believe would solve this issue.

What do you think?

Thanks,

**Comment by josx** [comment]
Look at https://github.com/josx/ra-data-feathers/issues/90#issuecomment-458593910

My comment:

> 
> So I think that the current work you have done, must be changed with a fn that flat only props not in ($lte, $gt, and the other on the feathers doc)
> check https://docs.feathersjs.com/api/databases/querying.html
> 
> In other words We need a conditional flatting object function.

It seems that We never have done this.

2 things: 
- We need to confirm I was right, Can you test if deep props are working with a simple equal.
- If that OK, can you do a PR for that?

**Comment by fabioptoi** [comment]
I just tested with simple equal and it's not working... It's being translated to `?rating[score]=1` on the query string...
I believe we need something like your suggestion of a conditional flatting object function. If you agree, I can create a PR with this modification

**Comment by josx** [comment]
Also  take account of what version of feathers and react-admin are you using.
Please do a PR (including tests), but first if you have time would be great if you can do a simple working example showing this problem (just files, code in gist, or codebox, or fiddle).

**Comment by fabioptoi** [comment]
Hey, sorry about the delay...

I created a codesandbox with the bug example: https://codesandbox.io/s/white-tree-2fmo7?fontsize=14&hidenavigation=1&theme=dark
If you insert a number in the "Rating" filter and check the Network tab on inspect you'll see the request being made to the backend.

My packages versions:
`@feathersjs/client: 3.5.5`
`react-admin: 2.2.0`
`ra-data-feathers: 2.5.0`

I'm working on the PR right now and I'll post it here as soon as I'm done with it

**Comment by fabioptoi** [comment]
Here it is: https://github.com/josx/ra-data-feathers/pull/138

**Comment by josx** [comment]
great! thanks a lot!
