### ISSUE TITLE
$in query operator not properly supported

### ISSUE THREAD

**Issue by alex-all3dp** [josx/ra-data-feathers#140]
Filter params with the [$in operator](https://docs.feathersjs.com/api/databases/querying.html#in-nin) like: 
```javascript
{ filter: { name: { $in: ['abc, 'def'] } } }
```
should be passed as is to the feathers client in order to result in query parameters of the format:
```
/path?name[$in]=abc&name[$in]=def
```

The `flatten` function in `restClient.js` incorrectly translates the input filter incorrectly to the following query:
```javascript
{ 'name.$in': ['abc', 'def'] }
```
which results in the query parameters: `/path?name.$in[0]=abc&name.$in[1]=def`

Simply adding `$in` to the `queryOperators` (as `stopKeys` parameter input) results in the correct query format
```javascript
{ name: { $in: ['abc', 'def'] } }
```
which results in the query parameters `/path?name[$in][0]=abc&name[$in][1]=def`

**Comment by josx** [comment]
@alex-all3dp 
good catch, can you recheck if the last commit fix this problem.

**Comment by josx** [comment]
after you confirmation i will release a new version

**Comment by alex-all3dp** [comment]
Hi @josx,
thank you for the quick response and fix! That commit works.

We just encountered that it would be necessary for us to support even more operators, e.g. from https://github.com/feathersjs-ecosystem/feathers-objection#query-operators. Other users may want to use query operators from other feathers adapters as well.

Would it be possible to make a change that allows to pass custom queryOperators and merge them with the currently hardcoded defaults?

**Comment by josx** [comment]
I think it would be great, to have that feature.
Can you make a PR on that? (please also include an example on how to do it in README)

**Comment by alex-all3dp** [comment]
@josx https://github.com/josx/ra-data-feathers/pull/142
