### ISSUE TITLE
File upload

### ISSUE THREAD

**Issue by AshotN** [josx/ra-data-feathers#163]
I am not sure if this is in scope for this project. But I can't figure out how to have Feather JS accept a file from `<FileInput>`

Can someone point give some pointers? Thanks!

**Comment by josx** [comment]
it is out of the scope, but i can share with you some legacy code on how to do it:

client:

```js
const dataProvider = restClient(feathersClient, { id: '_id', usePatch: true });

export class OperacionCreate extends Component {
  constructor(props) {
    super(props);
    this.state = {
      currentFile: null,
      result: null,
      isSaving: false
    }
    this.clickHandler = this.handleClick.bind(this)
    this.fileHandler = this.onFileChange.bind(this)
  }
  onFileChange(file) {
    this.setState({currentFile: file})
  }
  handleClick() {
    if (!this.state.isSaving && this.state.currentFile){
      this.setState({isSaving: true})
      convertFileToBase64(this.state.currentFile).then((convertedFile)=>{
        dataProvider(CREATE, 'operaciones', { data: {uri: convertedFile}})
        .then((resp) => {
          this.setState({result: resp.data.data})
        }).finally(()=> {
          this.setState({isSaving: false})
        })
      })
    }
  }
  render() {
    return (
      <Create {...this.props} title="Importar Operaciones">
        <SimpleForm toolbar={<OperacionToolbar isSaving={this.state.isSaving} handleClick={this.clickHandler}/>} redirect={false} >
          <FileInput onChange={this.fileHandler} source="uri" label="Planilla de Operacion" accept="application/vnd.ms-excel" validate={[required()]}>
            <FileField source="src" title="title" />
          </FileInput>
          {
            this.state.result ?
              <ResultadoDeCarga result={this.state.result}/>
              : null
          }
        </SimpleForm>
      </Create>
    );
  }
}
```

**Comment by AshotN** [comment]
Thank you kindly for this, that exactly what I needed. On a similar note, is there a way to set the form as a `enctype="multipart/form-data"`? Thanks again for the help.

**Comment by strarsis** [comment]
@josx: It would be nice if the `FeathersJS` `react-admin` data provider also adds file upload handling.
Currently the data provider has to be decorated with file upload handlers (https://marmelab.com/react-admin/doc/2.8/DataProviders.html#decorating-your-data-provider-example-of-file-upload).

**Comment by josx** [comment]
It would be very nice to have this feature.
Anyone can help with this?

**Comment by strarsis** [comment]
IMHO one (server-side) hook is needed for accepting uploaded files, an optional, 2nd (server-side) hook for adding the path of uploaded files to a record and the `ra-data-feathers` provider needs the extra functionality for handling file/image fields.

There is `feathers-blob` that offers some abstraction. The stores for it are a bit outdated though.

**Comment by josx** [comment]
Some clues:
- https://docs.feathersjs.com/cookbook/express/file-uploading.html
- https://gist.github.com/rravichaudhary/7f6a5f3967c923a1c5432416e3bfd463
