### ISSUE TITLE
`createMany` unsupported

### ISSUE THREAD

**Issue by strarsis** [josx/ra-data-feathers#174]
The `createMany` method is unsupported:
`FeathersJS restClient action type createMany`

It is very useful for some bulk operations, like a CSV import from `react-admin`.

**Comment by josx** [comment]
I dont see createMany in the reactadmin doc as available, where did you see it?
I have check it here https://marmelab.com/react-admin/DataProviders.html

**Comment by strarsis** [comment]
Maybe this is just a special action introduced by `react-admin-import-csv`?
https://github.com/benwinding/react-admin-import-csv/blob/9b7b840f76270fe7c444710881ed781a8d83c830/README.md#reducing-requests-createmany-and-updatemany

In that case the action has to be added by decorator. I initially had issues adding it - but found out that `ra-data-feathers` uses a function which has to be wrapped for decoration: https://github.com/josx/ra-data-feathers/issues/176
