### ISSUE TITLE
Production build: `Uncaught (in promise) Error: Failed to execute 'fetch' on 'Window': Illegal invocation`

### ISSUE THREAD

**Issue by strarsis** [josx/ra-data-feathers#177]
When starting the production build of `react-admin`, `react-admin` stays at the loading screen and this error occurs:
````
Uncaught (in promise) Error: Failed to execute 'fetch' on 'Window': Illegal invocation
````
Edit: Apparently this happens when the FeathersJS server is not reachable (network/CORS issues).
But nothing in the network tab in Developer Tools.
A much more descriptive error message would be nice.

**Comment by josx** [comment]
It seems that you can have problems with FETCH.
mmm Browser version maybe?

https://github.com/Airtable/airtable.js/issues/230

**Comment by strarsis** [comment]
@josx: I replaced Fetch with axios. And now it works. But I still want to use Fetch!

The API is reachable by the browser and another React app - though without authentication (JWT). 

With Fetch, the network tab for production `react-admin` shows no connection attempt to the API whatsoever.
`react-admin` works flawlessly in development (`yarn start`) though, with either axios or Fetch.

**Comment by strarsis** [comment]
So the `this` context of `window.fetch` got lost somehow. `window.fetch.bind(window)` or something like that has to be used.
https://stackoverflow.com/questions/10743596/why-are-certain-function-calls-termed-illegal-invocations-in-javascript

**Comment by josx** [comment]
So, try to share this in feathers doc, would be illuminating.

**Comment by strarsis** [comment]
@josx: Yes, I created a new PR in the FeathersJS `docs` repository.
