### ISSUE TITLE
`react-admin` `v4` support

### ISSUE THREAD

**Issue by strarsis** [josx/ra-data-feathers#182]
Does `ra-data-feathers` officially support the [new `react-admin` `v4` release](https://marmelab.com/blog/2022/04/08/react-admin-v4-goodbye-redux.html)?
I want to migrate the existing `react-admin` `v3` app to `v4`, but I have to be sure that `ra-data-feathers` still works afterwards.

**Comment by josx** [comment]
v4 It is very new, a few hours by now.

We need to read  
- https://marmelab.com/react-admin/Upgrade.html

**Comment by josx** [comment]
No time to test it out, but if you upgrade react-admin to 4, then run tests maybe we are going to have a clue.

Anyways two more things: 
1) Imports: dont know if it is exporting constants (https://github.com/josx/ra-data-feathers/blob/master/src/restClient.js#L1-L11)
2) maybe Some  Changed Signature Of Data Provider Hooks, but i am not sure

**Comment by strarsis** [comment]
Migrated the admin app to v4 and tested with the current `ra-data-feathers`, works fine so far...
Tests + official support for `v4` would be great though.

**Comment by josx** [comment]
What do you think we need to do to support v4? How you experienced any problem? any specific test to write?

**Comment by josx** [comment]
great! 
if you want to do integration tests would be perfect!
