### ISSUE TITLE
Suggestion: Change package name to reflect upgrade from AOR to RA

### ISSUE THREAD

**Issue by nicholasnelson** [josx/ra-data-feathers#71]
The naming convention shown in the react-admin documentation [here](https://marmelab.com/react-admin/DataProviders.html) shows the included data providers are named in the form `ra-data-[provider name]`

It might be worth changing the naming of this module to something like `ra-data-feathers` from `aor-feathers-client`. This could help to improve visibility of the module and remove associations with the old admin-on-rest which is no longer supported.

As a side-note on improving visibility, it may also be worth adding `react-admin` to keywords in package.json.

**Comment by josx** [comment]
Ok it is done, just summarizing what has been done 

* Renamed github repo to ra-data-feathers
* Created a [new repo with the old repo name](https://github.com/josx/aor-feathers-client/blob/master/README.md)  
* npm deprecate over [aor-feathers-client](https://www.npmjs.com/package/aor-feathers-client)
* Upgrade source code files with new name
* New  keyword on package.json
* new release on ra-data-feathers 
* [PR on react-admin to update link ](https://github.com/marmelab/react-admin/pull/2358)

if there is something more to do please advice.
