### ISSUE TITLE
Support UPDATE_MANY

### ISSUE THREAD

**Issue by nicholasnelson** [josx/ra-data-feathers#76]
Per the [react-admin documentation on data providers](https://marmelab.com/react-admin/DataProviders.html#writing-your-own-data-provider), this project currently supports all request types, except UPDATE_MANY.

The project I'm currently working on has a use for UPDATE_MANY. I'll submit a PR to add this feature soon. Just creating this issue to avoid any doubling-up of work.

Should be fairly easy I think. From a brief look at it, should be possible to do in the same way as DELETE_MANY

**Comment by josx** [comment]
Thanks for inform. We will be wating for that PR ;)
