### ISSUE TITLE
Possible Improvement: Code Style

### ISSUE THREAD

**Issue by nicholasnelson** [josx/ra-data-feathers#79]
While writing tests for #76, I've noticed the quotes used in test/restClient.spec.js vary throughout the file.

For example, this 'describe' block uses different quoting for each of the two 'it' blocks:
```js
  describe('when called with CREATE', function () {
      //snip
    it("calls the client's create method with the data in params", function () {
      //snip
    });

    it('returns the data returned by the client in a "data" object', function () {
      //snip
    });
  });
```

I have a couple of questions raised by this:

- Is there a designated style guide this project should adhere to? Personally I've always liked the [Airbnb Javascript Style Guide](https://github.com/airbnb/javascript) and would suggest this
- Is it worth considering adding linting somewhere? Possibly in the test config so it's picked up by CI checks before merging PRs?

For the purposes of getting #76 done now, I'm working under the assumption that single quotes are the preferred option.

**Comment by josx** [comment]
* For linting we can use eslint with [airbnb](https://www.npmjs.com/package/eslint-config-airbnb)
* I am using [lint-staged](https://github.com/okonet/lint-staged) in another project, we can also use it here

**Comment by nicholasnelson** [comment]
👍 
Happy for me to have a crack at a PR for that?

**Comment by sgobotta** [comment]
I could add an .eslint configuration file using the airbnb extension. Let me know if you're ok with that or something else should be added to complete this issue.
