### ISSUE TITLE
Improvement: Performant bulk-actions

### ISSUE THREAD

**Issue by nicholasnelson** [josx/ra-data-feathers#81]
The performance of bulk-actions could likely be improved.

Currently UPDATE_MANY and DELETE_MANY make multiple calls to the Feathers client, one for each ID to be updated/deleted. This is based on [ra-data-simple-rest](https://marmelab.com/react-admin/DataProviders.html#usage), which handles bulk actions like this because there isn't a 'standard' REST way to handle multi-item changes. Feathers doesn't have this limitation.

Per the [Feathers documentation](https://docs.feathersjs.com/api/services.html#removeid-params), when making a call to 'remove', 'update', or 'patch', the 'id' argument can be _null_. In this case, params.query will be used to determine which records the action will affect.

We could do something like:
```js
  case DELETE_MANY:
    return service.remove(null, {
      query: {
        [idKey]: {
          $in: params.ids
        }
      }
    });
```

The downside of this is that it would no longer be possible to use the Feathers client with a non-Feathers  REST service (which might not support $in). I'm not sure if this is possible **anyway**, might be good to test this.

To avoid any issues, this could be done as an optional enhancement. i.e. make the current behavior default, set 'optimiseFeathersBulkActions: true' in the restClient options to enable single-call-bulk-actions.

**Comment by josx** [comment]
I dont think it 's worth it to think about using feathers client with a non feathers rest service.

But We need to be sure that it will work with all the database adpaters.

**Comment by nicholasnelson** [comment]
It should work with all database adaptors.

GET_MANY already relies on $in:

```js
      case GET_MANY:
        let ids = params.ids || []
        query[idKey] = {$in: ids}
        query['$limit'] = ids.length
        return service.find({query})
```

 If a database adaptor doesn't support $in (which would be a failing on the part of the adaptor as $in is part of the common query syntax for Feathers), GET_MANY will already be failing.

Didn't realise this was the case when I wrote the original issue. We're not adding / relying on any currently unused features by doing this. Is there a problem with this you can see that I'm missing?

**Comment by josx** [comment]
I read again doc on feathers site, and $in is a common way to query for all adapters (the only adapter conflict zone is on querying by search)

**Comment by josx** [comment]
In addition, it is better to have a delete many just in on query (not cycling for each id)

**Comment by taylorgoodallau** [comment]
Hey @josx, if there are no objections to having this issue addressed still, I will submit a PR once I've completed code changes.

**Comment by josx** [comment]
Would be great, please go on

**Comment by taylorgoodallau** [comment]
Still working on this one, need to update the response mapping to fix a broken test. 
Should have some time in the next couple of days to have it completed.

**Comment by josx** [comment]
Ok @taylorgoodallau no worries, We can wait :)
