### ISSUE TITLE
Support for feathers v3?

### ISSUE THREAD

**Issue by Raidus** [josx/ra-data-feathers#86]
Hi,

I've setup correctly the newest feathers backend and verified functionality. My feathersClient.js looks like

```js
import feathers from '@feathersjs/client'

const host = 'http://localhost:3030'

export default feathers()
  .configure(feathers.rest(host).fetch(window.fetch.bind(window)))
```

But after starting react-admin, I'll get following error:

![image](https://user-images.githubusercontent.com/8803882/48051952-e05fde00-e1a6-11e8-9e63-fb4eee3d706b.png)

Any ideas?

Thanks

**Comment by Raidus** [comment]
Oh sorry, stupid mistake. After posting the screenshot, I've realized that I've initialized the dataprovider not correctly.

It should be 

```js
class App extends Component {
  constructor () {
    super()
    this.state = { dataProvider: null }
  }
  componentDidMount () {
    this.setState({ dataProvider: restClient(feathersClient, restClientOptions)})
  }

  render () {
    const { dataProvider } = this.state

    if (!dataProvider) {
      return <div>
               Loading
             </div>
    }

    return (
      <Admin dataProvider={dataProvider}>
        <Resource
          name='ranking'
          list={RankingList}
          create={RankingCreate}
          edit={RankingEdit} />
      </Admin>
    )
  }
}

export default App
```

**Comment by josx** [comment]
Ok @Raidus , will close this issue, but anyways it is good source of documentation that anyone searching can discover.
