### ISSUE TITLE
Fix yarn issue for codeship

### ISSUE THREAD

**Issue by josx** [josx/ra-data-feathers#88]
Test won't pass in codeship since yarn is not installing eslint correctly.

https://github.com/airbnb/javascript/issues/1508

**Comment by nicholasnelson** [comment]
Added PR #95 which addresses this.

Problem seems to have been incompatibility between Eslint and the version of node configured for CircleCI (~7). I opted to update Node to fix this. Another possible fix would be to find a version of Eslint which supports Node v7, however given Node v7 is EOL and was never an LTS release, I think it makes more sense to update Node to 10.15.1 LTS.
