### ISSUE TITLE
ReferenceField is sending wrong request

### ISSUE THREAD

**Issue by juanpasolano** [josx/ra-data-feathers#92]
I'm using feathers `^3.2.3` and the `<ReferenceField />` is apparently sending the wrong request.

[Currently](https://github.com/josx/ra-data-feathers/blob/master/src/restClient.js#L33) `query[idKey] = { $in: ids };` is being used but that returns an empty array. Changing  it to `query[idKey] = ids;` does work for me.

I'm pretty new to feathers but I would assume this is a feathers v2 vs v3 thing?

Happy to make a PR if this makes sense toy you guys.

**Comment by juanpasolano** [comment]
@josx Thank you so much for clarifying. i'll close this since it appears to be a problem with my code.

**Comment by josx** [comment]
no problem, if i can help you just write me.
